# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LastFmSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LastFmSwift
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireObjectMapper', '5.2.0'

  target 'LastFmSwiftTests' do
    inherit! :search_paths
	pod 'Alamofire', '4.8.2'
	pod 'AlamofireObjectMapper', '5.2.0'
  end

end
