# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DiscogsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiscogsSwift
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'

  target 'DiscogsSwiftTests' do
    inherit! :search_paths
  end

end
